### ISSUE TITLE
Add a generic parameter.

### ISSUE THREAD

**Issue by FlorinProfeanuVEGO** [kartik1998/pdf-images#12]
Hello,

Unfortunately, the jpg extension (issue #10) does not solve the transparency issue. I mean it removes transparency but for one example I am working with, it turns the white background of the PDF into black in JPG.

I found this link https://www.imagemagick.org/discourse-server/viewtopic.php?t=31014 that gives a solution for PDFs. Indeed, the below command works better:
convert -density 300x300 -units pixelsperinch Test.pdf -background white -alpha background -alpha off -antialias -compress none +adjoin Test.png

During my tests I found that this one is OK as well:
convert -density 300 -quality 100 Test.pdf -alpha background -alpha off Test.png

What I would like you to do, if you agree, is to add a generic parameter where we can add things like -alpha background -alpha off.
Obviously is up to the user to add correct options here.

Florin

**Comment by kartik1998** [comment]
Hi @FlorinProfeanuVEGO ,
Sorry my response is extremely late. (Had some health issues for some months to deal with). 
I'm thinking of taking a more freehand approach to an issue like this given that different users might face different issues based on the kind of pdfs they have. 

So having a seperate arguement which allows them to add such arguements (and more) makes a lot of sense to me. 

However we currently use `execFileSync` to run the shell command which I want to discontinue because of it's synchronous nature so i've decided to add an another method to convert i.e. `ImageMagick.convertAsync`.
